{
    "targets": [
        {
            "target_name": "nacl",
            "include_dirs": [
                "include",
            ],
            "cflags_cc":  ["-fexceptions", "-funroll-loops"],
            "sources": [ "../nacl.cc",
                "nacl/crypto_auth/hmacsha256/ref/hmac.c",
                "nacl/crypto_auth/wrapper-auth.cpp",
                "nacl/crypto_box/curve25519xsalsa20poly1305/ref/after.c",
                "nacl/crypto_box/curve25519xsalsa20poly1305/ref/before.c",
                "nacl/crypto_box/curve25519xsalsa20poly1305/ref/box.c",
                "nacl/crypto_box/curve25519xsalsa20poly1305/ref/keypair.c",
                "nacl/crypto_box/wrapper-box.cpp",
                "nacl/crypto_box/wrapper-keypair.cpp",
                "nacl/crypto_box/wrapper-open.cpp",
                "nacl/crypto_core/hsalsa20/ref2/core.c",
                "nacl/crypto_core/salsa20/ref/core.c",
                "nacl/crypto_stream/xsalsa20/ref/stream.c",
                "nacl/crypto_stream/xsalsa20/ref/xor.c",
                "nacl/crypto_stream/salsa20/ref/stream.c",
                "nacl/crypto_stream/salsa20/ref/xor.c",
                "nacl/crypto_hash/sha512/ref/hash.c",
                "nacl/crypto_hash/wrapper-hash.cpp",
                "nacl/crypto_hashblocks/sha512/inplace/blocks.c",
                "nacl/crypto_hashblocks/wrapper-empty.cpp",
                "nacl/crypto_onetimeauth/poly1305/53/auth.c",
                "nacl/crypto_onetimeauth/poly1305/53/verify.c",
                "nacl/crypto_onetimeauth/wrapper-auth.cpp",
                "nacl/crypto_onetimeauth/wrapper-verify.cpp",
                "nacl/crypto_verify/16/ref/verify.c",
                "nacl/crypto_verify/32/ref/verify.c",
                "nacl/crypto_scalarmult/curve25519/donna_c64/base.c",
                "nacl/crypto_scalarmult/curve25519/donna_c64/smult.c",
                "nacl/crypto_scalarmult/wrapper-base.cpp",
                "nacl/crypto_scalarmult/wrapper-mult.cpp",
                "nacl/crypto_secretbox/wrapper-box.cpp",
                "nacl/crypto_secretbox/wrapper-open.cpp",
                "nacl/crypto_secretbox/xsalsa20poly1305/ref/box.c",
                "nacl/crypto_sign/edwards25519sha512batch/ref/fe25519.c",
                "nacl/crypto_sign/edwards25519sha512batch/ref/ge25519.c",
                "nacl/crypto_sign/edwards25519sha512batch/ref/sc25519.c",
                "nacl/crypto_sign/edwards25519sha512batch/ref/sign.c",
                "nacl/crypto_sign/wrapper-keypair.cpp",
                "nacl/crypto_sign/wrapper-sign.cpp",
                "nacl/crypto_sign/wrapper-sign-open.cpp",
                "nacl/randombytes/devurandom.c",
            ]
        }
    ]
}
